- name: Select production keys to save locally
  delegate_to: "{{ hostvars[groups['moc']|first]['inventory_hostname'] }}"
  shell: "find /home/{{ ansible_user }}/{{ NETWORK_NAME }}/validator-keys/{{ groups['validator'].index(ansible_play_batch|first)+1 }} -type f | egrep .*mining_.*"
  register: production_keys

- name: Save file
  delegate_to: "{{ hostvars[groups['moc']|first]['inventory_hostname'] }}"
  fetch: 
    src: "{{ item }}"
    dest: "/tmp/{{ NETWORK_NAME }}/production-keys/{{ groups['validator'].index(ansible_play_batch|first)+1 }}/"
    flat: yes
  with_items: "{{ production_keys.stdout_lines }}"

- name: Gather validator address
  become: false
  delegate_to: "localhost"
  shell: "find /tmp/{{ NETWORK_NAME }}/production-keys/{{ groups['validator'].index(ansible_play_batch|first)+1 }}/ | egrep .*mining_.*.json | tail -n 1 | sed -e 's/.*mining_\\(.*\\).json/\\1/'"
  register: addresses
    
- name: Gather JSON
  become: false
  delegate_to: "localhost"
  shell: "find /tmp/{{ NETWORK_NAME }}/production-keys/{{ groups['validator'].index(ansible_play_batch|first)+1 }}/ | egrep .*mining_{{ addresses.stdout }}.json | tail -n 1"
  register: json_keystore
  
- name: Gather key
  become: false
  delegate_to: "localhost"
  shell: "find /tmp/{{ NETWORK_NAME }}/production-keys/{{ groups['validator'].index(ansible_play_batch|first)+1 }}/ | egrep .*mining_{{ addresses.stdout }}.key | tail -n 1"
  register: key

- include_role:
    name: '{{ playbook_dir }}/deployment-playbooks/roles/validator'
  vars:
    username: "validator"
    GENESIS_NETWORK_NAME: "{{ NETWORK_NAME }}"
    MINING_ADDRESS: "0x{{ addresses.stdout }}"
    MINING_KEYPASS: "{{ lookup ('file', key.stdout) }}"
    MINING_KEYFILE: "{{ lookup ('file', json_keystore.stdout) }}"

- name: Register bytecode variable
  block:    
    - name: get contracts.json content
      delegate_to: "{{ groups['moc']|first }}"
      slurp:
        src: "/home/{{ ansible_user }}/{{ NETWORK_NAME }}/contracts.json"
      register:
        contracts_coded
    - set_fact:
        contracts_json: "{{ contracts_coded['content'] | b64decode }}"
  
- name: Adjust RewardTransfer configs
  lineinfile:
    path: /home/validator/poa-scripts-validator/config.json
    regexp: '^.*\"addr\"\: .*'
    line: '        "addr": "{{ contracts_json.KEYS_MANAGER_ADDRESS }}",'
    
- name: make sure npm transferRewardToPayoutKey modules installed
  npm:
    path: "/home/validator/poa-scripts-validator/transferRewardToPayoutKey"
  become: true
  become_user: "validator"
  
- name: Start all POA services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - poa-parity
    - poa-pm2
    - poa-netstats
    
- name: "Clear /tmp/{{ NETWORK_NAME }}/production-keys/ dir"
  delegate_to: localhost
  file:
    state: absent
    path: "/tmp/{{ NETWORK_NAME }}/production-keys/"