- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group_name if resource_group_name != '' else NETWORK_NAME+'rg' }}"
    location: "{{ region }}"
    auth_source: "{{ 'cli' if lookup ('env', 'ANSIBLE_AZURE_AUTH_SOURCE') == '' else lookup ('env', 'ANSIBLE_AZURE_AUTH_SOURCE') }}"
  environment:
    AZURE_SUBSCRIPTION_ID: "{{ lookup ('env','ARM_SUBSCRIPTION_ID') }}"
    AZURE_CLIENT_ID: "{{ lookup ('env','ARM_CLIENT_ID') }}"
    AZURE_SECRET: "{{ lookup ('env','ARM_CLIENT_SECRET') }}"
    AZURE_TENANT: "{{ lookup ('env','ARM_TENANT_ID') }}"
    #Variables, that are set for Terraform are not the same required by Ansible